### PR TITLE
add Logoutption with command and locations

### PR DESCRIPTION
**Pull request by ahmed608**
You can Log out to select new character with command and Locations in map to press e and select new character

### CODE REVIEW

**Comment by outsider31000** [comment]
Hi!  
This is a good idea, althought there is no requirement for this to be implemented in the script as you are only triggering an event,you can do this from any script.
But I will merge this , if you remove DrawText, this isnt fivem... let's  use prompts.

also might be best adding blips to it.
thank you.

**Comment by ahmed608** [comment]
> Hi! This is a good idea, althought there is no requirement for this to be implemented in the script as you are only triggering an event,you can do this from any script. But I will merge this , if you remove DrawText, this isnt fivem... let's use prompts.
> 
> also might be best adding blips to it. thank you.

ok you check now

**Comment by outsider31000** [comment]
thank you , was this tested?

**Comment by ahmed608** [comment]
> thank you , was this tested?

tested now and everything good 

image


image

**Comment by ahmed608** [comment]
> thank you , was this tested?

hello

**Comment by outsider31000** [comment]
this commit will be revert. 
the idea is good but it wont work
scripts use player drop events to remove data, just like vorp core and vorp inventory , if the player dont leave the server the data will still continue in the scripts.

for this reason it will be removed.

**Pull request merged**
