### PR TITLE
Random initial player spawn

### PR DESCRIPTION
**Pull request by zurv4n**
# Pull request template
> [!IMPORTANT]
> Please complete all fields. PRs will not be merged if any fields are incomplete. Be respectful, and keep in mind that it may take some time for your PR to be reviewed.
>
> Bear in mind refactors are up to the developers and not it's contributors after all we are the ones giving support when needed. if they are big changes I suggest you to release it under your name instead.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Motive for This Pull Request
Having all new players spawn in the same place can get old. This allows server owners to create a list of places where new characters will spawn

### Provide a brief explanation of why these changes are being proposed and what they aim to achieve.
It will add variety for players to start in a new location, possibly adding RP elements.

### Explain the necessity of these changes and how they will impact the framework or its users.
It isn't necessary, just a nice to have. 

### Please describe the tests you have conducted to verify your changes. Provide instructions so we can reproduce these tests. Also, list any relevant details for your test configuration.

- [X] Tested with latest vorp scripts
- [X] Tested with latest artifacts

## Notes if any
Figured I would share with the community. The code added allows for the list and chance to be as long or short, the function will adjust to the length of the list and total possible chance. As an addition, it adds a flag so if a server owner does not want, they do not have to use. But if they turn the flag to true in config, then one of the random locations will be selected. It only applies to initial spawn.

### CODE REVIEW

**Comment by outsider31000** [comment]
Hi!

I don't mind the feature, but there are some things that need to be changed
- use only one table ConfigSpawnCoords  users can add more or use just one , theres no need to add a new variable to use random or not they can just remove and leave one entry to not be random.

 - the random function its iterating twice the same table, not sure why is that needed?
 
 heres a simplified way without needing a chance or iterating tables
 ```lua
 function iniSpawn()
	local numSpawns = #Config.RandSpawnCoords
	local randomIndex = math.random(1, numSpawns) -- min 1 max the amount of entries this will never create an nil index error
	local selectedSpawn = Config.RandSpawnCoords[randomIndex] 
	return selectedSpawn.position, selectedSpawn.heading
end
```
consider adding this implementation please
thanks.

**Comment by zurv4n** [comment]
That is a very good simplification and think it could work. If you wish to, please incorporate it.  The reason for the first iteration was to allow a weight for each spawn point so some spawn points have a higher chance of occurrence than others. My submission is to make higher chance of spawning in a town versus at one of the outer train stations. With that, I can make the changes you recommended or you can. Either way, thank you for the tips. your implementation is much cleaner. Thank you.

**Comment by outsider31000** [comment]
yes make the changes.
and just use the SpawnCoords table instead of creating a new one.
also no need to add and index [1] =  , the table already has index by adding the brackets { }

**Comment by zurv4n** [comment]
completed.

**Pull request merged**
