### PR TITLE
Update Spanish Translate

### PR DESCRIPTION
**Pull request by goldeninmyneck**
# Pull request template
> [!IMPORTANT]
> Please complete all fields. PRs will not be merged if any fields are incomplete. Be respectful, and keep in mind that it may take some time for your PR to be reviewed.
>
> Bear in mind refactors are up to the developers and not it's contributors after all we are the ones giving support when needed. if they are big changes I suggest you to release it under your name instead.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Motive for This Pull Request
Simple corrections of the translation that had been wrongly translated from Spanish. In some places "lable" was used instead of "label".
### Provide a brief explanation of why these changes are being proposed and what they aim to achieve.
Avoid having unrecognized field errors when using the Spanish language.

### Explain the necessity of these changes and how they will impact the framework or its users.
Avoid having unrecognized field errors when using the Spanish language.

### Please describe the tests you have conducted to verify your changes. Provide instructions so we can reproduce these tests. For example NickName =  was listed as "apodo =" part of an earlier mistranslation.

- [x] Tested with latest vorp scripts
- [x] Tested with latest artifacts

## Notes if any
explanation field

### CODE REVIEW

**Comment by outsider31000** [comment]
Hi

there seems to be conflicts with this pull request  can you try to solve it.

**Comment by goldeninmyneck** [comment]
Hello! 
Yes, I'm going to see it. How strange...

**Comment by goldeninmyneck** [comment]
Note that they are listed above as "lable" and not as label

**Comment by RealStonerGamer** [comment]
it was fixed in  update the other day i believe

**Comment by outsider31000** [comment]
image
this cant be merged as it has conflics, try to solve them press that button if you dont know , i'll do it .

**Comment by goldeninmyneck** [comment]
readyy

**Comment by goldeninmyneck** [comment]
It was ready in the previous update, you are right. I just changed apodo = Apodo to Nickname = Apodo

**Pull request merged**
