### PR TITLE
feat: Outfits + improvements + fixes

### PR DESCRIPTION
**Pull request by XakraD**
# Pull request template
> [!IMPORTANT]
> Please complete all fields. PRs will not be merged if any fields are incomplete. Be respectful, and keep in mind that it may take some time for your PR to be reviewed.
>
> Bear in mind refactors are up to the developers and not it's contributors after all we are the ones giving support when needed. if they are big changes I suggest you to release it under your name instead.

## Type of change

- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Motive for This Pull Request
By wanting to implement the script, and I fixed what I saw wrong.

### Provide a brief explanation of why these changes are being proposed and what they aim to achieve.
- When changing clothes, the tint of the used clothes will be obtained and the menu will be updated, to change the tint with the used value.
- Fixed the light not starting in the store. (DrawLight option has also been added to store locations)
- The amount of character rotation has been lowered, it was spinning too fast.
- Fixed the store camera, when moving the camera it initially appeared at the highest point. Also on some occasions the camera moved to the coordinates of the character's creation.
- Added the Scenario option in the npcs of the store. For the npc to make some animation. (Option can be set to false)
- Removed extra space from 'total' languages.
- Changed 'lable' language to 'label'.
- Added outfit menu
- Changed the store zoom from INPUT_CURSOR_ACCEPT_HOLD to INPUT_CONTEXT_ACTION, it will not take 1s to start changing the zoom.
- 

### Explain the necessity of these changes and how they will impact the framework or its users.
These changes are to improve the user experience and functions of the script.

### Please describe the tests you have conducted to verify your changes. Provide instructions so we can reproduce these tests. Also, list any relevant details for your test configuration.
Tested with all updated framework scripts, performing different tests using the store and checking that no errors appear.

- [x ] Tested with latest vorp scripts
- [x ] Tested with latest artifacts

## Notes if any
explanation field

## SQL
CREATE TABLE IF NOT EXISTS `outfits` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `identifier` varchar(45) NOT NULL,
  `charidentifier` int(11) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `comps` longtext DEFAULT NULL,
  `compTints` longtext CHARACTER SET armscii8 COLLATE armscii8_general_ci DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=2931 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;

### CODE REVIEW

**Comment by outsider31000** [comment]
Hi 
There's a couple things that  need to be changed here 
image
1 - I dont see a  reason  why this function was removed. needs to be added back to avoid duplicated code in which was added for that purpose.

image
2- In this situation the tint values need to be reset other wise everytime you apply a new variation it also applies tints disabling its true colors (tints are options)

image
3 -  in here when scrolling through other components we need to reset the tints or they keep being applied and users wont be able to see its true color, not everything needs tints same as above

tints are an option not a obligation to be added
as for the rest  it seems fine once these are fixed we will merge them.

Thank you for your contribution.

**Comment by XakraD** [comment]
> Hi There's a couple things that need to be changed here image 1 - I dont see a reason why this function was removed. needs to be added back to avoid duplicated code in which was added for that purpose.
> 
> image 2- In this situation the tint values need to be reset other wise everytime you apply a new variation it also applies tints disabling its true colors (tints are options)
> 
> image 3 - in here when scrolling through other components we need to reset the tints or they keep being applied and users wont be able to see its true color, not everything needs tints same as above
> 
> tints are an option not a obligation to be added as for the rest it seems fine once these are fixed we will merge them.
> 
> Thank you for your contribution.

What do you mean in point 2? Tints are obtained from used clothing, it will not appear at 0.

For example, you change the pants and you get dye 1 with value 85, you change it to 86, when you return to 85 it will have the original color, you should not change it from 0.

Regarding point 3, do you mean that the SetElement function of the value sets it to 0 as it was previously?

**Comment by XakraD** [comment]
I will make changes constantly, in case you update and not have conflicts, at the moment everything is not finished.

**Comment by outsider31000** [comment]
Hi!

There's some things  you need to change here.

Something we need to keep in mind is to keep the same format of code
image
This needs to have a `SetTimeout` just like some lines above have is being used. `SetTimeout` is an async Wait funciton.

image
This is a server side event, we need to remove the AddEventHandler for security. because other clients can trigger this event when its only a server side event.

image
This control was changed And I dont see a reason why. it needs to be added back. if there isn't an issue theres no need to be changed.

image
Here I noticed you have added  the components to become a string when they are in fact numbers, Numbers cannot be compared with strings, this needs to go back as it was , unless you have a reason for it?

image
If you look closely the tints are being added to the values of the elements , it needs to put back as they were thats what the setElements are there for.

image
I also see no reason for this to have been removed we dont need to remove something "clothing"  that doesnt exist.

image
image
I also see no reason for this to be removed, needs to be added back.

image
Trying to understand what does this code do, you remove all components and add them back again ? This is to open the outfit store its not even being applied, not sure why this is needed. outfts are to be applied when you selecte them, not when you enter the menu.

image
This needs to be removed, category is already defined bydefault in utils.lua file no need to loop this to remove the variables comp.

image
In here there's no need to be a global , needs to be added as local.

image
In here you are using a different export while in other places you use oxmysql.

image
We can also remove these AddEventHandlers , they are not server side events, they are net events only. 

So we have some work to do here and I ask you to please next time you need to describe and add each commit explaining the changes cause I spent alot of time here just to figure out what you trying to do...

Also keep in mind by contributing this much you will need to support your changes in the vorp discord, I haven't seen you in vorp helping anyone... 
Otherwise the comit will be reverted Because we are not going to maintain other peoples code obviously.

Once these are resolved it will be merged.
If you have any questions please ask here.

Thank you for your contribution as always.

**Comment by XakraD** [comment]
The INPUT_CURSOR_ACCEPT_HOLD control has a delay and took longer than the right click to zoom. That's why it was changed, it can be verified using both of them.
image

Tostring has been added to the compTints index of the ConvertTableComps function, because when the LoadComps function is used with the outfit's compTints column, the index is of type string. I have seen that maybe when used in other parts of the code the index is a number, I have to check and correct it, if necessary I will convert the table to the index with numbers..
image

Regarding the for that removes clothes, I recreated that one so that it doesn't remove hair or beard when changing outfits.
image

Here the content of the PlayerClothing list is deleted because when using the store, reopening the menu/changing outfit, changing the cup again restores the previous clothes plus the clothes changed in the preview.

For example, if I added an accessory in the preview, but did not save it, when I returned to the store and changed an outfit, it would appear again.
image

Now I make the changes you mentioned, the next updates I will comment on the changes.

**Comment by outsider31000** [comment]
300199402-57a41ccd-873c-4d58-9099-3b980c5b021c
when you leave the store you can clean this table there not needing to do this

**Comment by XakraD** [comment]
## Changes from previous updates (not commented)
- Setting the clothing category or variant to 0 will remove the secondary text component. Also fixed the remove component button.
- When changing clothing component categories, the first variant on the list will always be set. (With the current tint)

## Changes of 'IndexTintCompsToNumber, SetTimeout, callback events'
- Eliminated the if that sets the category value to 1, it does not allow equipping the last component.
- Changed the `SetTimeout` to freeze when starting the store, which freezes the user until the menu is completely started, to prevent movement while loading.
- Added `IndexTintCompsToNumber` function to use tints when setting outfits and updating component cache. (By default the index of the comps was type string and should be type number)
- Changed removal of `PlayerClothing[i]` to `{ comp = -1 }`
- Changed the outfit events using the core api.

**Comment by XakraD** [comment]
## Changes
- Removed several calls from the `IsPedReadyToRender` function in `Applycomponents`, because it is already executed in the `ReloadAllComponents` function
- A loop has been added to the component and variant sliders. The component slider is from -1 to the maximum (at 0 the component is removed), the variants slider from 1 to the maximum.

**Comment by outsider31000** [comment]
thank you for your contribution

**Pull request merged**
