### PR TITLE
Added palette variable

### PR DESCRIPTION
**Pull request by KadDarem**
# Pull request template
> [!IMPORTANT]
> Please complete all fields. PRs will not be merged if any fields are incomplete. Be respectful, and keep in mind that it may take some time for your PR to be reviewed.
>
> Bear in mind refactors are up to the developers and not it's contributors after all we are the ones giving support when needed. if they are big changes I suggest you to release it under your name instead.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Motive for This Pull Request
Add the possibility of using a different color palette than the default from the clothes game data. 

### Provide a brief explanation of why these changes are being proposed and what they aim to achieve.
Add the possibility to use a "palette" variable in compTint value. If the "palette" value is nil, keep using the default palette as before.

### Explain the necessity of these changes and how they will impact the framework or its users.
Can open the possibility to add a palette selector in the clothing store menu

### Please describe the tests you have conducted to verify your changes. Provide instructions so we can reproduce these tests. Also, list any relevant details for your test configuration.

- [x] Tested with latest vorp scripts
- [x] Tested with latest artifacts

### CODE REVIEW

**Comment by outsider31000** [comment]
Hi

I don't see  the option to change pallet types? I see the variable to apply it if ther's one , but there's nothing in the menu to set witch one to use. 

How can the pallete type be choosen ?

**Comment by KadDarem** [comment]
I didnt edit the menu. 

I just edited the backend to make it compatible with clothing store that allow the palette swap.

**Comment by outsider31000** [comment]
well then this isn't a feature for vorp characters as you said in the comments, you need to edit the menu other wise how is people able to use this?

**Comment by outsider31000** [comment]
You are making a pull request in vorp characters repository  for a feature that exist in your scripts, sorry but this not acceptable.
The feature needs to exist here for users to use it, other wise it's not a feature.

If you have any questions let me know.

**Comment by KadDarem** [comment]
The menu is edited. It's now possible to change the color palette.

**Comment by outsider31000** [comment]
Hi

There's just a coulpe things I noticed here.
image
Can we move this to the main config? since it's not for shops please.

Another thing I noticed
image
This is a server side event , adding a net event allows clients to trigger these.

if you have any questions let me know.

**Comment by KadDarem** [comment]
1. I moved ConfigShops.palettes into Config.clothesPalettes

2. About the added the RegisterNetEvent : 
It's currently possible to trigger the event to open the character selection on the client side with "vorp_character:server:GoToSelectionMenu". 
So, adding the possibility to trigger the spawn of a character could not be a problem. It's like calling the character selection and selecting the first character.

**Comment by outsider31000** [comment]
Ah 
I see what you mean , then if you can please add  a Config.DevMode to lock that net event to dev mode only

**Comment by KadDarem** [comment]
It's not the case for the opening of character selection.

Why this event is more critical ?

**Comment by outsider31000** [comment]
all right

Thanks for the contribution

**Comment by outsider31000** [comment]
Hi sorry again @KadDarem  
I just noticed this feature is missing from the commands.lua file the pallet  feature
are you able to do it? 

sorry I dindt noticed it before.

**Comment by KadDarem** [comment]
What do you mean?

I tried commands and my custom palette is right apply on my clothes.

**Comment by outsider31000** [comment]
Yeah never mind it's added to the cache. 
I forgot, thanks again

**Pull request merged**
